services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/?authSource=${MONGO_AUTH_DB}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - mongodb

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../docs:/app/docs
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  airflow-init:
    build:
      context: ../airflow
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username ${AIRFLOW_ADMIN_USER}
      --firstname Airflow --lastname Admin --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL} --password ${AIRFLOW_ADMIN_PASSWORD}"

  airflow-webserver:
    build:
      context: ../airflow
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init
      - postgres
      - mongodb
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/jobs:/opt/airflow/jobs
      - ../dwh:/opt/airflow/dbt
      - ../dwh/profiles:/opt/airflow/dbt_profiles
      - ../docs:/opt/airflow/reports

  airflow-scheduler:
    build:
      context: ../airflow
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: scheduler
    depends_on:
      - airflow-init
      - postgres
      - mongodb
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/jobs:/opt/airflow/jobs
      - ../dwh:/opt/airflow/dbt
      - ../dwh/profiles:/opt/airflow/dbt_profiles
      - ../docs:/opt/airflow/reports

volumes:
  mongo_data:
  postgres_data:
